### ISSUE TITLE
Grails 4 support

### ISSUE THREAD

**Issue by pjdvmalan** [grails/grails-spring-security-oauth2#7]
Please indicate when this plugin will be upgraded to support Grails 4.

**Comment by puneetbehl** [comment]
I have just merged PR #6. Could you please verify with the latest BUILD-SNAPSHOT.

**Comment by jrAtAustin** [comment]
I started migrating my app from Grails 3.3.11 to Grails 4.0.12 and I have a dependency on this plugin. Is there a version of this plugin that's compatible with Grails 4.0.12? I also have a Okta OAUTH2 provider plugin that uses this plugin. Will I need to change my plugin?

**Comment by purpleraven** [comment]
@puneetbehl As I can see, comparability with Grails 4 broken. The library even can't be downloaded in usual way.
I don't see the jar in the IDEA dependencies list, but gradle tell nothing about wrong dependency path. I see spring-security-oauth2 in gradle dependancy tree, but during compilation no class can be found

`compile 'org.grails.plugins:spring-security-oauth2:2.0.0-SNAPSHOT'`

```
unable to resolve class grails.plugin.springsecurity.oauth2.token.OAuth2SpringToken 
```
   
Finally I manually downloaded the 2.0.0-RC-1 jar from   https://mvnrepository.com/artifact/org.grails.plugins/spring-security-oauth2/2.0.0-RC1 , but got error in line
`def callbackURL = getConfigValue(providerService.providerID, "callback") ? baseURL + getConfigValue(providerService.providerID, "callback") : baseURL + "/oauth2/" + providerService.getProviderID() + "/callback"` 

```
java.lang.AbstractMethodError: null
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
	at grails.plugin.springsecurity.oauth2.SpringSecurityOauth2BaseService.$tt__registerProvider(SpringSecurityOauth2BaseService.groovy:136)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:97)
	at grails.plugin.springsecurity.oauth2.SpringSecurityOauth2BaseService$_registerProvider_closure5.doCall(SpringSecurityOauth2BaseService.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)

```
 
It fails on this getter providerService.providerID   

I'm using grailsVersion=4.0.13 with java 8
Looks like incompatibility in groovy-java build-run version. The plugin now build on Grails 5 

Could you please release version 2.0.0 for Grails 4 on Grails 4 please?
